version: "3.8"

services:
  php:
    build: ./services/php
    volumes:
      - ./htdocs:/var/www/html
      - ./services/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./services/mariadb/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - db